package com.failuredb.failure;
import com.failuredb.repository.*; import com.failuredb.user.*; import jakarta.validation.Valid; import jakarta.validation.constraints.*; import java.util.*; import org.springframework.http.HttpStatus; import org.springframework.security.core.annotation.AuthenticationPrincipal; import org.springframework.security.core.userdetails.UserDetails; import org.springframework.web.bind.annotation.*; import org.springframework.web.server.ResponseStatusException;
@RestController
public class FailureController {
 private final FailureJpaRepository failures; private final FailureRepositoryJpa repos; private final UserAccountRepository users; FailureController(FailureJpaRepository failures,FailureRepositoryJpa repos,UserAccountRepository users){this.failures=failures;this.repos=repos;this.users=users;}
 @GetMapping("/api/failures") public List<FailureResponse> all(){return failures.findAllByOrderByCreatedAtDesc().stream().map(FailureResponse::of).toList();}
 @GetMapping("/api/repos/{repoId}/failures") public List<FailureResponse> byRepo(@PathVariable UUID repoId){return failures.findByRepositoryIdOrderByCreatedAtDesc(repoId).stream().map(FailureResponse::of).toList();}
 @PostMapping("/api/repos/{repoId}/failures") @ResponseStatus(HttpStatus.CREATED) public FailureResponse create(@PathVariable UUID repoId,@AuthenticationPrincipal UserDetails principal,@Valid @RequestBody CreateFailure request){if(principal==null)throw new ResponseStatusException(HttpStatus.UNAUTHORIZED); FailureRepository repo=repos.findById(repoId).orElseThrow(()->new ResponseStatusException(HttpStatus.NOT_FOUND)); UserAccount author=users.findByUsernameIgnoreCase(principal.getUsername()).orElseThrow(()->new ResponseStatusException(HttpStatus.UNAUTHORIZED)); return FailureResponse.of(failures.save(new Failure(repo,author,request.title(),request.summary(),request.context(),request.expectedOutcome(),request.actualOutcome(),request.rootCause(),request.warningSigns(),request.lessonsLearned(),request.prevention(),request.severity(),request.tags(),request.occurredYear())));}
 @GetMapping("/api/search") public List<FailureResponse> search(@RequestParam(defaultValue="") String q){if(q.isBlank())return all();return failures.findByTitleContainingIgnoreCaseOrSummaryContainingIgnoreCaseOrderByCreatedAtDesc(q,q).stream().map(FailureResponse::of).toList();}
 public record CreateFailure(@NotBlank @Size(max=220) String title,@NotBlank @Size(max=1000) String summary,String context,String expectedOutcome,String actualOutcome,String rootCause,String warningSigns,String lessonsLearned,String prevention,@Min(1) @Max(10) int severity,@Size(max=500) String tags,@Min(1900) @Max(2100) Integer occurredYear){}
 public record FailureResponse(String id,String title,String summary,String context,String expectedOutcome,String actualOutcome,String rootCause,String warningSigns,String lessonsLearned,String prevention,int severity,String tags,Integer occurredYear,String repository,String repositoryId,String category,String author,java.time.Instant createdAt){static FailureResponse of(Failure f){return new FailureResponse(f.getId().toString(),f.getTitle(),f.getSummary(),f.getContext(),f.getExpectedOutcome(),f.getActualOutcome(),f.getRootCause(),f.getWarningSigns(),f.getLessonsLearned(),f.getPrevention(),f.getSeverity(),f.getTags(),f.getOccurredYear(),f.getRepository().getTitle(),f.getRepository().getId().toString(),f.getRepository().getCategory(),f.getAuthor().getUsername(),f.getCreatedAt());}}
}
