import { FormEvent, StrictMode, useEffect, useMemo, useState, type ReactNode } from 'react'
import { createRoot } from 'react-dom/client'
import './styles.css'

const API = 'http://localhost:8080/api'
type Repo = { id:string; title:string; description:string; category:string; industry:string; owner:string; visibility:string }
type Failure = { id:string; title:string; summary:string; rootCause:string; warningSigns:string; lessonsLearned:string; prevention:string; severity:number; tags:string; occurredYear:number; repository:string; repositoryId:string; category:string; author:string; createdAt:string }
const auth = () => localStorage.getItem('failuredb-basic') || ''
async function request(path:string, options:RequestInit = {}) { const response = await fetch(API + path, { ...options, headers: { 'Content-Type':'application/json', ...(auth() ? { Authorization: auth() } : {}), ...(options.headers || {}) } }); if (!response.ok) { const body = await response.json().catch(() => ({})); throw new Error(body.detail || body.message || `Request failed (${response.status})`) } return response.status === 204 ? null : response.json() }

function App() {
 const [repos,setRepos]=useState<Repo[]>([]), [failures,setFailures]=useState<Failure[]>([]), [query,setQuery]=useState(''), [notice,setNotice]=useState(''), [user,setUser]=useState(localStorage.getItem('failuredb-user') || ''), [modal,setModal]=useState<'auth'|'repo'|'failure'|null>(null)
 const load=async()=>{try { const [r,f]=await Promise.all([request('/repos'),request('/failures')]);setRepos(r);setFailures(f)} catch(e){setNotice(e instanceof Error ? e.message : 'Could not load data')} }
 useEffect(()=>{load()},[])
 useEffect(()=>{ const listener=(event:KeyboardEvent)=>{if((event.ctrlKey||event.metaKey)&&event.key.toLowerCase()==='k'){event.preventDefault();document.getElementById('search')?.focus()}};window.addEventListener('keydown',listener);return()=>window.removeEventListener('keydown',listener)},[])
 const visible=useMemo(()=>!query ? failures : failures.filter(f=>`${f.title} ${f.summary} ${f.tags} ${f.category}`.toLowerCase().includes(query.toLowerCase())),[failures,query])
 const signed=!!user
 const onLogged=(name:string)=>{setUser(name);localStorage.setItem('failuredb-user',name);setModal(null);setNotice(`Welcome, ${name}. Your contributions are attributed to you.`)}
 const signout=()=>{localStorage.removeItem('failuredb-basic');localStorage.removeItem('failuredb-user');setUser('');setNotice('You have signed out.')}
 return <><header><a className="brand" href="/">FAILURE<span>DB</span></a><nav><a href="#explore">Explore</a><a href="#patterns">Patterns</a><a href="#lessons">Lessons</a><a href="#premortem">Pre-mortem</a></nav><div className="head-actions">{signed ? <><span className="user">@{user}</span><button className="quiet" onClick={signout}>Sign out</button><button onClick={()=>setModal('failure')}>+ Record failure</button></> : <><button className="quiet" onClick={()=>setModal('auth')}>Sign in</button><button onClick={()=>setModal('auth')}>Create account</button></>}</div></header>
 <main><section className="hero"><div><p className="eyebrow">A KNOWLEDGE BASE FOR HARD-WON LESSONS</p><h1>Learn from what<br/><em>already went wrong.</em></h1><p className="lede">FailureDB turns scattered stories and incident reports into structured, evidence-aware knowledge anyone can learn from.</p><div className="search"><span>⌕</span><input id="search" value={query} onChange={e=>setQuery(e.target.value)} placeholder="What are you trying to avoid?"/><kbd>⌘ K</kbd></div><div className="examples"><button onClick={()=>setQuery('SaaS')}>Why SaaS startups fail</button><button onClick={()=>setQuery('migration')}>Why migrations fail</button><button onClick={()=>setQuery('marketplace')}>Why marketplaces fail</button></div></div><aside className="signal"><div className="signal-top"><span>LIVE SIGNAL</span><i></i></div><strong>{failures.length || '—'}</strong><p>structured reports<br/>in the knowledge base</p><hr/><div className="statrow"><span>{repos.length}</span><small>repositories</small><span>Evidence first</span></div></aside></section>
 {notice && <div className="notice">{notice}<button onClick={()=>setNotice('')}>×</button></div>}
 <section id="explore" className="content"><div className="section-heading"><div><p className="eyebrow">EXPLORE THE DATABASE</p><h2>Recent failure reports</h2></div>{signed && <button onClick={()=>setModal('repo')}>Create repository</button>}</div>{visible.length ? <div className="cards">{visible.map(f=><article className="card" key={f.id}><div className="card-meta"><span>{f.category}</span><b className={`sev s${f.severity}`}>Impact {f.severity}/10</b></div><h3>{f.title}</h3><p>{f.summary}</p><div className="root"><b>Root cause</b>{f.rootCause || 'Investigation in progress'}</div><footer><span>{f.repository} · {f.occurredYear || 'Undated'}</span><span>{f.tags}</span></footer></article>)}</div> : <div className="empty"><h3>No reports yet</h3><p>Start the knowledge base with a structured report. Every report makes a future decision less risky.</p>{signed ? <button onClick={()=>setModal('repo')}>Create the first repository</button> : <button onClick={()=>setModal('auth')}>Create an account to contribute</button>}</div>}</section>
 <section className="framework"><p className="eyebrow">NOT A FEED. A DECISION SYSTEM.</p><div><h2>Turn a failure into reusable knowledge.</h2><div className="steps"><p><b>01</b> Capture context</p><p><b>02</b> Test the evidence</p><p><b>03</b> Trace the cause</p><p><b>04</b> Extract prevention</p></div></div></section>
 <section className="repositories"><div className="section-heading"><div><p className="eyebrow">FAILURE REPOSITORIES</p><h2>Active research spaces</h2></div></div><div className="repo-grid">{repos.slice(0,6).map(r=><article className="repo" key={r.id}><span>{r.category}</span><h3>{r.title}</h3><p>{r.description}</p><footer>@{r.owner} · {r.visibility.toLowerCase()}</footer></article>)}</div></section></main>
 {modal==='auth'&&<AuthModal close={()=>setModal(null)} logged={onLogged}/>} {modal==='repo'&&<RepoModal close={()=>setModal(null)} done={()=>{setModal(null);setNotice('Repository created. Add the first structured report.');load()}}/>} {modal==='failure'&&<FailureModal repos={repos} close={()=>setModal(null)} done={()=>{setModal(null);setNotice('Failure report published to the knowledge base.');load()}}/>}</>
}
function AuthModal({close,logged}:{close:()=>void;logged:(name:string)=>void}){const [register,setRegister]=useState(true),[error,setError]=useState(''),[busy,setBusy]=useState(false);const submit=async(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();const d=new FormData(e.currentTarget);const username=String(d.get('username')), password=String(d.get('password'));setBusy(true);setError('');try{if(register)await request('/auth/register',{method:'POST',body:JSON.stringify({username,email:d.get('email'),password})});const login=await request('/auth/login',{method:'POST',body:JSON.stringify({username,password})});localStorage.setItem('failuredb-basic',login.authorization);logged(login.user.username)}catch(x){setError(x instanceof Error?x.message:'Unable to sign in')}finally{setBusy(false)}};return <Modal close={close} title={register?'Create your contributor account':'Welcome back'}><form onSubmit={submit}>{register&&<><label>Username<input name="username" required pattern="[a-zA-Z0-9_-]{3,40}" placeholder="your-name"/></label><label>Email<input name="email" type="email" required placeholder="you@example.com"/></label></>} {!register&&<label>Username<input name="username" required autoComplete="username"/></label>}<label>Password<input name="password" type="password" minLength={8} required autoComplete={register?'new-password':'current-password'} placeholder="Minimum 8 characters"/></label>{error&&<p className="form-error">{error}</p>}<button type="submit" disabled={busy}>{busy?'Signing in…':register?'Create account':'Sign in'}</button><button type="button" className="link" onClick={()=>{setRegister(!register);setError('')}}>{register?'Already contribute? Sign in':'New here? Create an account'}</button></form></Modal>}
function RepoModal({close,done}:{close:()=>void;done:()=>void}){const [error,setError]=useState('');const submit=async(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();const d=new FormData(e.currentTarget);try{await request('/repos',{method:'POST',body:JSON.stringify(Object.fromEntries(d))});done()}catch(x){setError(x instanceof Error?x.message:'Could not create repository')}};return <Modal close={close} title="Create a failure repository"><form onSubmit={submit}><label>Repository title<input name="title" required placeholder="Why Our Delivery Startup Failed"/></label><label>What will it document?<textarea name="description" required placeholder="A concise, factual description of the investigation."/></label><label>Category<select name="category"><option>Startup</option><option>Engineering</option><option>Product</option><option>Software</option><option>Operations</option><option>Research</option></select></label><label>Industry<input name="industry" placeholder="Food technology"/></label><input type="hidden" name="visibility" value="PUBLIC"/>{error&&<p className="form-error">{error}</p>}<button>Create repository</button></form></Modal>}
function FailureModal({repos,close,done}:{repos:Repo[];close:()=>void;done:()=>void}){const [repo,setRepo]=useState(repos[0]?.id||''),[error,setError]=useState('');const submit=async(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();if(!repo){setError('Create a repository before adding a report.');return}const d=Object.fromEntries(new FormData(e.currentTarget));try{await request(`/repos/${repo}/failures`,{method:'POST',body:JSON.stringify({...d,severity:Number(d.severity),occurredYear:d.occurredYear?Number(d.occurredYear):null})});done()}catch(x){setError(x instanceof Error?x.message:'Could not publish report')}};return <Modal close={close} title="Record a failure"><form onSubmit={submit}><label>Repository<select value={repo} onChange={e=>setRepo(e.target.value)}>{repos.length?repos.map(r=><option value={r.id} key={r.id}>{r.title}</option>):<option value="">No repository available</option>}</select></label><label>Failure title<input name="title" required placeholder="Retention fell below the viable threshold"/></label><label>Short summary<textarea name="summary" required placeholder="What happened, in one clear paragraph?"/></label><div className="twocol"><label>Year<input name="occurredYear" type="number" min="1900" max="2100" placeholder="2026"/></label><label>Impact<select name="severity" defaultValue="6">{[1,2,3,4,5,6,7,8,9,10].map(x=><option key={x}>{x}</option>)}</select></label></div><label>Root cause<textarea name="rootCause" placeholder="What underlying condition caused the failure?"/></label><label>Warning signs<textarea name="warningSigns" placeholder="What should have alerted the team earlier?"/></label><label>Lessons learned<textarea name="lessonsLearned" placeholder="Write an actionable lesson, not a slogan."/></label><label>How to prevent this<textarea name="prevention" placeholder="What should a future team test or change?"/></label><label>Tags<input name="tags" placeholder="retention, unit economics, startup"/></label>{error&&<p className="form-error">{error}</p>}<button>Publish structured report</button></form></Modal>}
function Modal({title,children,close}:{title:string;children:ReactNode;close:()=>void}){return <div className="overlay" role="dialog" aria-modal="true"><div className="modal"><button className="close" onClick={close}>×</button><p className="eyebrow">CONTRIBUTE KNOWLEDGE</p><h2>{title}</h2>{children}</div></div>}
createRoot(document.getElementById('root')!).render(<StrictMode><App/></StrictMode>)
